# Generated by Django 2.1.7 on 2019-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0035_auto_20190320_1018'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saveProperty',
            field=models.ManyToManyField(blank=True, related_name='under_property', to='homepage.PropertyListADCreation'),
        ),
    ]
