# Generated by Django 2.1.7 on 2019-04-01 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_savepropertytracker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.BooleanField(default=False)),
                ('market', models.BooleanField(default=False)),
                ('hospital', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=120)),
                ('distance_from_location', models.IntegerField()),
                ('price_start_range', models.CharField(max_length=5)),
                ('price_end_range', models.CharField(max_length=5)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
    ]
