# Generated by Django 2.1.7 on 2019-03-18 10:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import homepage.models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20190219_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPropertyListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.models.list_Property_images)),
                ('image_content', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListRooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('bed_available', models.IntegerField(default=1)),
                ('private_room', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deposit', models.CharField(max_length=40)),
                ('rent', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Property List Room',
            },
        ),
        migrations.CreateModel(
            name='RSImagesMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.models.main_upload_image)),
                ('image_name', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('image_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.RSImages')),
            ],
            options={
                'verbose_name': 'Home Enlarged Image',
                'verbose_name_plural': 'Home Enlarged Images',
            },
        ),
        migrations.CreateModel(
            name='UserScheduleVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, max_length=35, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='propertylistadcreation',
            name='extra_charges',
            field=models.CharField(default='2000', max_length=4),
        ),
        migrations.AddField(
            model_name='propertylistadcreation',
            name='features',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertylistadcreation',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='propertylistadcreation',
            name='offers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listproperty',
            name='contact',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Please enter a valid number.', regex=re.compile('(0/91)?[7-9][0-9]{9}'))]),
        ),
        migrations.AlterField(
            model_name='propertylistadcreation',
            name='room_type',
            field=models.CharField(default='shared', max_length=40),
        ),
        migrations.AddField(
            model_name='propertylistrooms',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.PropertyListADCreation'),
        ),
        migrations.AddField(
            model_name='imagespropertylisting',
            name='image_for',
            field=models.ForeignKey(limit_choices_to={'rent': 7000}, on_delete=django.db.models.deletion.CASCADE, to='homepage.PropertyListADCreation'),
        ),
    ]
