# Generated by Django 2.1.7 on 2019-02-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_propertylistadcreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistadcreation',
            name='bed_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertylistadcreation',
            name='furnished',
            field=models.CharField(default='Fully Furnished', max_length=30),
        ),
    ]
