# Generated by Django 2.1.7 on 2019-02-24 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_userschedulevist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserScheduleVist',
            new_name='UserScheduleVisit',
        ),
    ]
