# Generated by Django 2.1.7 on 2019-02-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20190224_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistadcreation',
            name='room_type',
            field=models.CharField(default='shared', max_length=40),
        ),
    ]
