# Generated by Django 2.1.7 on 2019-02-24 12:39

from django.db import migrations
import homepage.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20190224_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistadcreation',
            name='property_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=homepage.models.upload_prop_image),
        ),
    ]
