# Generated by Django 2.1.7 on 2019-02-26 09:07

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_auto_20190225_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsimages',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.upload_image),
        ),
    ]
