# Generated by Django 2.1.7 on 2019-02-26 10:09

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_rsimages_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsimages',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.main_upload_image),
        ),
    ]
