# Generated by Django 2.1.7 on 2019-02-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20190226_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rsimages',
            name='main_image',
        ),
    ]
