# Generated by Django 2.1.7 on 2019-02-26 12:59

from django.db import migrations, models
import django.db.models.deletion
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_remove_rsimages_main_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSImagesMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=homepage.models.main_upload_image)),
                ('image_name', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('image_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.RSImages')),
            ],
        ),
    ]
