# Generated by Django 2.1.7 on 2019-03-01 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20190228_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesPropertyListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='list_Property_images')),
                ('image_content', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('image_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.PropertyListADCreation')),
            ],
        ),
    ]
