# Generated by Django 2.1.7 on 2019-03-02 08:25

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_imagespropertylisting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagespropertylisting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=homepage.models.list_Property_images),
        ),
        migrations.AlterField(
            model_name='userschedulevisit',
            name='contact',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
