# Generated by Django 2.1.7 on 2019-03-05 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_auto_20190302_0825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rsimagesmain',
            options={'verbose_name': 'Home Enlarged Image', 'verbose_name_plural': 'Home Enlarged Images'},
        ),
    ]
