# Generated by Django 2.1.7 on 2019-03-14 09:39

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_auto_20190314_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listproperty',
            name='contact',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(message='Please enter a valid number.', regex=re.compile('(0/91)?[7-9][0-9]{9}'))]),
        ),
    ]
