# Generated by Django 2.1.7 on 2019-03-15 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0023_propertylistrooms'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertylistrooms',
            options={'verbose_name_plural': 'Property List Room'},
        ),
    ]
