# Generated by Django 2.1.7 on 2019-03-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0024_auto_20190315_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagespropertylisting',
            name='image_for',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='homepage.PropertyListADCreation'),
        ),
    ]
