# Generated by Django 2.1.7 on 2019-03-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0026_auto_20190315_0554'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistrooms',
            name='bed_available',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='propertylistrooms',
            name='private_room',
            field=models.BooleanField(default=False),
        ),
    ]
