# Generated by Django 2.1.7 on 2019-03-18 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0029_propertylistadcreation_extra_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistadcreation',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='propertylistadcreation',
            name='available_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
