# Generated by Django 2.1.7 on 2019-03-19 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0030_auto_20190318_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistadcreation',
            name='available_on',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
