# Generated by Django 2.1.7 on 2019-03-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0031_auto_20190319_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertylistadcreation',
            name='available_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
