# Generated by Django 2.1.7 on 2019-03-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0032_auto_20190319_0528'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistadcreation',
            name='total_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
