# Generated by Django 2.1.7 on 2019-02-19 07:32

from django.db import migrations, models
import homepage.models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_listproperty_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListADCreation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_type', models.CharField(max_length=120)),
                ('about_property', models.TextField()),
                ('rent', models.CharField(max_length=25)),
                ('deposit', models.CharField(max_length=10)),
                ('area', models.CharField(max_length=120)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('property_image', models.ImageField(blank=True, null=True, upload_to=homepage.models.upload_prop_image)),
                ('gender', models.CharField(default='Boys/Girls/Family', max_length=30)),
            ],
        ),
    ]
