# Generated by Django 2.1.7 on 2019-02-19 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_auto_20190219_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylistadcreation',
            name='room_type',
            field=models.CharField(default='Shared Room', max_length=40),
        ),
    ]
